---
name: linting
on:
  - pull_request

jobs:
  Markdownlint:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4
      - name: Markdown Lint
        uses: actionshub/markdownlint@v3.1.4

  Dockerfilelint:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4
      - name: Dockerfile Lint
        uses: burdzwastaken/hadolint-action@1.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HADOLINT_ACTION_DOCKERFILE_FOLDER: .
